# Generated by Django 2.2.5 on 2021-12-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.CharField(default='', max_length=130),
        ),
        migrations.AlterField(
            model_name='course',
            name='sno',
            field=models.AutoField(default='0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='timestamp',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
