# Generated by Django 2.2.5 on 2021-12-25 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20211225_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Course')),
            ],
        ),
    ]
