# Generated by Django 2.2.5 on 2021-12-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20211225_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
