# Generated by Django 2.2.5 on 2021-12-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_auto_20211225_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.AddField(
            model_name='topics',
            name='slug',
            field=models.CharField(default='', max_length=130),
        ),
    ]
