# Generated by Django 2.2.5 on 2021-12-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0010_auto_20211228_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='photo',
            field=models.ImageField(default='', upload_to='tutorials/topics'),
        ),
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(default='', upload_to='tutorials/course'),
        ),
    ]
