# Generated by Django 3.2.5 on 2021-12-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(blank=True),
        ),
    ]
